# -*- coding: utf-8 -*-
"""audio translate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fT2Dju7Dpv1eJ6_EvyswqNydFLvzEJcI
"""

!apt-get install -y libportaudio2
!pip install openai-whisper transformers sentencepiece gTTS soundfile


import whisper
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer
from gtts import gTTS
from IPython.display import Audio

print(" Loading Whisper model (small)...")
whisper_model = whisper.load_model("small")

print("Loading Translation model (facebook/m2m100_418M)...")
m2m_model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(m2m_model_name)
m2m_model = M2M100ForConditionalGeneration.from_pretrained(m2m_model_name)

# Functions

def transcribe_audio(path, language=None):
    result = whisper_model.transcribe(path, language=language)
    return result.get("text", "").strip()

def translate_text(text, src_lang="ta", tgt_lang="en"):
    tokenizer.src_lang = src_lang
    encoded = tokenizer(text, return_tensors="pt")
    generated_tokens = m2m_model.generate(**encoded, forced_bos_token_id=tokenizer.get_lang_id(tgt_lang))
    return tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]

def text_to_speech(text, lang="en", out_file="out.mp3"):
    tts = gTTS(text=text, lang=lang)
    tts.save(out_file)
    print(f"Saved translated speech as {out_file}")
    return Audio(out_file)

def speech_to_speech_from_file(audio_file, src_lang="ta", tgt_lang="en"):

    # 1. Speech → Text
    text = transcribe_audio(audio_file, language=src_lang)
    print("📝 Tamil Transcription:", text)

    # 2. Translate
    translated = translate_text(text, src_lang=src_lang, tgt_lang=tgt_lang)
    print(" English Translation:", translated)

    # 3. Text → Speech
    return text_to_speech(translated, lang=tgt_lang)

# Generate sample Tamil audio for testing

tamil_text = "வணக்கம் நண்பா! இன்று நம்ம project demo செய்வோம்."
tts = gTTS(text=tamil_text, lang="ta")
tts.save("tamil_test.wav")
print("Sample Tamil audio saved: tamil_test.wav")

speech_to_speech_from_file("tamil_test.wav", src_lang="ta", tgt_lang="en")